### ISSUE TITLE
#US01 - Função de login 

### ISSUE THREAD

**Issue by eduardopessoa89** [eduardopessoa89/Point-of-Sale#4]
**Descrição:**
        Quero fazer login na aplicação com um usuário. Caso não consiga, quero poder recuperar 
        minha senha.
**Critério de aceitação:**
	Utilizando o e-mail e senha de um usuário existente, deve poder acessar a tela inicial.
	Quando o usuário for criado ele terá uma senha temporária que deve ser alterada quando ele acessar o sistema a primeira vez, o usuário terá que definir sua senha.

**Tasks:** 

- [x] #T01 - Criar Tela de Login (Frontend)

- [x] #T02 - Refatorar Autenticação (Backend)

- [x] #T04 - Implementar Migrations (Backend)

- [x] #T05 - Criar permissions default

- [x] #T06 - Implementar Refresh Token (Backend)
