### ISSUE TITLE
#US02 - Cadastrar Usuário

### ISSUE THREAD

**Issue by eduardopessoa89** [eduardopessoa89/Point-of-Sale#5]
**Descrição:**
    Como usuário administrador, eu posso cadastrar novos usuários.	

**Critério de aceitação:**
Após Logar no sistema, o Usuário com perfil administrador deve clicar no item de menu, Usuários , deve ser aberta uma tela com um botão “Novo”. 

**Ao ser clicado, este botão deve abrir um formulário com os seguintes campos:**
**Nome:**  textual, máximo de 250 caracteres, obrigatório
**CPF:** textual, máximo de 20 caracteres, obrigatório, com validação se é um cpf válido, único e Máscara.
**Email:** textual, com validação se é um e-mail válido, único, obrigatório e validação de e-mail
**Senha:** textual, com validação de confirmação de senha, obrigatório e máscara
**Cargo:** idRole, obrigatório, Select
**Telefone:** Telefone, com validação e máscara 

**Não deve ser possível:**

- Criar Usuário com o mesmo e-mail e/ou CPF de um já existente

- Criar Usuário contendo número no campo Nome

- Criar Usuário com caracteres especiais (p.e. %$#@!&) no campo Nome

- Criar Usuário com menos de 3 caracteres no campo Nome

- Criar Usuário com e-mail inexistente

**Tasks:**

- [x] #T01 - Adicionar relacionamento com a tabela Role (Backend)

- [x] #T02 - Definir Roles na tabela de Usuários (Backend)

- [x] #T03 - Criar formulário de cadastro de Usuário (Frontend)

- [x] #T04 - Fazer Validações no backend (Backend)

- [x] #T05 - Fazer Validações e Máscaras no Frontend (Frontend)
