### ISSUE TITLE
#US03 - Listar Usuários

### ISSUE THREAD

**Issue by eduardopessoa89** [eduardopessoa89/Point-of-Sale#6]
**Descrição:**
Após logar no sistema, o usuário com role administrador, ao clicar no item de menu “Usuários” deve ver uma lista de usuários cadastrados no sistema contendo o nome e o cargo de cada usuário. Também  poderá pesquisar pelo Nome ou filtrar pelo Cargo dos usuários.

**Critério de aceitação:**
	Após logar no sistema, ao clicar no item de menu “Usuários” quero ver uma lista de usuários cadastrados no sistema contendo o nome e o cargo de cada usuário. 
	A listagem deve conter colunas para **Nome**,  **Cargo** e **Ações**.

**Na coluna Ações, devem existir três botões para cada item:**
- **Visualizar** - Navega para a página de visualização de todos os dados do Funcionário.
- **Editar** - Navega para a página de edição, onde os dados serão editados.
- **Deletar** - Dispara um janela, solicitando a confirmação para deletar.
	Ao pesquisar pelo nome, a listagem deve mostrar todos os usuários que contenham o nome pesquisado
	Ao filtrar pelo cargo, a listagem deve mostrar todos os usuários que possuam o cargo buscado

**Tasks:**

- [ ] #T01 - Criar tela de listagem de Usuários (Frontend)

- [ ] #T02 - Criar endpoint para retorno todos os Usuários não deletados do sistema (Backend)

- [ ] #T03 - Criar endpoint de filtro (Backend)

- [ ] #T04 - Criar campo de filtro na tela de listagem (Frontend)

- [ ] #T05 - Fazer paginação lazy no frontend (Frontend)

- [ ] #T06 - Criar paginação no backend (Backend)

- [ ] #T07 - Criar filtragem no back-end (Backend)
