### ISSUE TITLE
#US02 - Cadastrar Usuário

### ISSUE THREAD

**Issue by enosteteo** [eduardopessoa89/Point-of-Sale#7]
**Descrição:**
    Como usuário administrador, eu posso cadastrar novos usuários.	

**Critério de aceitação:**
    Após Logar no sistema, o Usuário com perfil administrador deve clicar no item de menu, Usuários , deve ser aberta uma tela com um botão “Novo”. 
    Ao ser clicado, este botão deve abrir um formulário com os seguintes campos:
- Nome:  textual, máximo de 250 caracteres, obrigatório
- CPF: textual, máximo de 20 caracteres, obrigatório, com validação se é um cpf válido, único e Máscara. 
- Email: textual, com validação se é um email válido, único, obrigatório e validação de email
- Senha: textual, com validação de confirmação de senha, obrigatório e máscara
- Confirmação de Senha: textual, com validação de confirmação de senha, obrigatório e máscara
- Cargo: idRole, obrigatório, Select
- Telefone: Telefone, com validação e máscara 

**Não deve ser possível:**
- criar Usuário com o mesmo email e/ou cpf de um já existente
- criar Usuário contendo número no campo Nome
- criar Usuário com caracteres especiais (p.e. %$#@!&) no campo Nome
- criar Usuário com menos de 3 caracteres no campo Nome
- criar Usuário com email inexistente

**Tasks:**
- [ ] #T01 - Criar tabelas Role e Permission na migration (Backend)
- [ ] #T02 - Atualizar atributos da tabela de Usuário (Add: CPF, CARGO, DELETED) 
- [ ] #T03 - Definir relacionamento com somente uma Role na tabela de Usuários(Backend)
- [ ] #T04 - Criar formulário de cadastro de Usuário (Frontend)
- [ ] #T05 - Fazer Validações no backend (Backend)
- [ ] #T06 - Fazer Validações no Frontend (Frontend)
- [ ] #T07 - Fazer Máscaras no Frontend (Frontend)
- [ ] #T08 - POC de toast para mensagens de erro na validação de dados
